# -*- coding: utf-8 -*-
"""SQLite VSS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_VuFKhyurldlspjinnjRXLwufiDgvJq7
"""

!pip install sqlite-vss

!pip install langchain

from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import SQLiteVSS
from langchain.document_loaders import TextLoader

loader = TextLoader("state_union.txt")
documents = loader.load()

"""# New Section"""

documents

# split it into chunks
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)
texts = [doc.page_content for doc in docs]

texts

!pip install sentence-transformers

# create the open-source embedding function
embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")

# load it in sqlite-vss in atable named state_union.
# the db_file parameter is the name of the file you want
# as your sqlite database.
db = SQLiteVSS.from_texts(texts=texts, embedding=embedding_function, table="state_union", db_file="vss.db")

query = "What did the president say about Ketanji Brown Jackson"
data = db.similarity_search(query)

# print results
data[0].page_content