apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: open-webui-ollama
    meta.helm.sh/release-namespace: app-dev-romel-campbell
    volume.beta.kubernetes.io/storage-provisioner: regeneron.com/aws-efs
    volume.kubernetes.io/storage-provisioner: regeneron.com/aws-efs
  labels:
    app.kubernetes.io/component: open-webui-ollama
    app.kubernetes.io/instance: open-webui-ollama
  name: open-webui-ollama
  namespace: app-dev-romel-campbell
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: aws-efs
  volumeMode: Filesystem
